import { Box, Flex, Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SideNav } from '@/app/ui/side-nav';
import { Provider } from './provider';
import '@radix-ui/themes/styles.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Provider>
          <Theme accentColor="violet" radius="medium">
            <Flex className="h-screen">
              <Box className="max-md:hidden">
                <SideNav />
              </Box>
              <Box grow={'1'}>
                <div className="h-full w-full">{children}</div>
              </Box>
            </Flex>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
