#!/usr/bin/env sh

# Source Husky script
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your project before committing'

# Run Prettier to format code
echo '🚀 Running Prettier to format code...'
if bun run prettier; then
    echo '🌈✨ Code styling with Prettier succeeded! ✨🌈'
    
    # Add formatted files to the staging area
    git add .
else
    echo '❌ Prettier encountered an error during formatting. Check the console for details.'
    exit 1
fi

# Build project
if ! bun run build; then
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.'
    exit 1
fi

# If everything passes, commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
