#!/usr/bin/env sh

# Source Husky script
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your project before committing'

# Check Prettier standards
if ! bun run prettier:check; then
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Running bun run prettier to fix issues...'
    
    # Run Prettier to format code
    if bun run prettier; then
        echo '🌈✨ Code styling with Prettier succeeded! ✨🌈'
    else
        echo '❌ Prettier encountered an error during formatting. Check the console for details.'
        exit 1
    fi
fi

# Build project
if ! bun run build; then
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.'
    exit 1
fi

# If everything passes, commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
